#!/bin/bash

FILE="/etc/squid3/squid.conf"

clear
echo -e "\033[01;36m LISTA DE PORTAS PERMITIDAS:\033[01;32m 0: RETORNAR AO MENU."
echo ""
 NUMBER=$(cat $FILE | grep "http_port" | cut -d " " -f2 | wc -l)
if [ $NUMBER = "0" ]; then
  echo -e "\033[01;33mVocê não possui nenhuma porta adicionanda no momento!"; echo ""
else
  echo -ne "\033[01;33m"; cat $FILE | grep "http_port" | cut -d " " -f2; echo ""
fi
echo -ne "\033[01;36m Digite uma porta para adicionar ao Proxy Squid:\033[01;37m "; read ADD
if [ -z $ADD ]; then
  echo ""
  echo -e "\033[01;37;41m Você digitou uma porta vazia. Tente novamente!\033[0m"
  sleep 3s
  adicionarporta
  exit
else
if [ "$ADD" = "0" ]; then
  adicionarporta
  exit
else
if echo "$ADD" | grep -q '[^0-9]'; then
  echo ""
  echo -e "\033[01;37;41m Porta inválida. Tente novamente!\033[0m"
  sleep 3s
  adicionarporta
  exit
else
if cat $FILE | grep "http_port" | cut -d " " -f2 | grep -xq "$ADD"; then
  echo ""
  echo -e "\033[01;37;41m Ops! Esta porta já está em uso. Tente outra porta!\033[0m"
  sleep 3s
  adicionarporta
  exit
else
if cat /etc/ssh/sshd_config | grep "Port" | cut -d " " -f2 | grep -xq "$ADD"; then
  echo ""
  echo -e "\033[01;37;41m Ops! Esta porta já está em uso. Tente outra porta!\033[0m"
  sleep 3s
  adicionarporta
  exit
else
if cat /etc/default/dropbear | grep -q "$ADD"; then
  echo ""
  echo -e "\033[01;37;41m Ops! Esta porta já está em uso. Tente outra porta!\033[0m"
  sleep 3s
  adicionarporta
  exit
else
  cat $FILE | head -11 > ports1.txt
  cat $FILE | grep "http_port" > ports2.txt
  cat $FILE | grep "#" > ports3.txt
  cat ports1.txt > $FILE
  cat ports2.txt >> $FILE
  echo "http_port $ADD" >> $FILE
  echo " " >> $FILE
  echo -e "visible_hostname ColtSEALS\n\nforwarded_for off\npipeline_prefetch on" >> $FILE
  echo " " >> $FILE
  cat ports3.txt >> $FILE
  rm p*
  service squid3 restart 1> /dev/null 2> /dev/null
  clear
  echo -e "\033[01;36m LISTA DE PORTAS PERMITIDAS:"
  echo ""
  echo -ne "\033[01;33m"; cat $FILE | grep "http_port" | cut -d " " -f2
  echo ""
  echo -e "\033[01;32m Porta adicionanda com sucesso!"
  echo -e "\033[01;32m Porta: $ADD"
fi
fi
fi
fi
fi
fi
echo ""
echo -ne "\033[01;36mA PERTE A TECLA ENTER..."
read ENTER
vpn
exit
