#!/bin/bash
b="\033[1;37m"
v="\033[1;32m"
Ver="\033[1;31m"
clear
echo -e "\033[0m                \033[47;30m ATUALIZANDO SCRIPT VPN... \033[0m" 
echo ""
if yum -y update 1>/dev/null 2>/dev/null
then
yum -y update 1>/dev/null 2>/dev/null
yum -y install git 1>/dev/null 2>/dev/null
git clone https://github.com/fuzileiros/vpn.git 1>/dev/null 2>/dev/null
cd CONFVPS
rm -rf README.md
rm -rf instalador
for arqs in `ls`
do
rm /bin/$arqs 2>/dev/null
mv $arqs /bin
chmod +x /bin/$arqs
done
echo -e "\033[0;32m  ATUALIZACAO FEITA COM SUCESSO"
echo -e "\033[0;32m  USE O COMANDO:\033[1;37m VPN"
echo -e "\033[0;32m:PARA VER OQUE MUDOU NESSA ATUALIZCAO...!"
else
clear
echo -e "\033[0m                \033[47;30mATUALIZANDO MENU VPN... \033[0m" 
echo ""
apt-get update 1>/dev/null 2>/dev/null
apt-get install -y git 1>/dev/null 2>/dev/null
git clone https://github.com/fuzileiros/vpn.git 1>/dev/null 2>/dev/null
cd VPN
rm -rf README.md
rm -rf instalador
for arqs in `ls`
do
rm /bin/$arqs 2>/dev/null
mv $arqs /bin
chmod +x /bin/$arqs
done
echo -e "\033[0;32m ATUALIZACAO FEITA COM SUCESSO"
echo -e "\033[0;32m USE O COMANDO:\033[1;37m VPN"
echo -e "\033[0;32m PARA VER OQUE MUDOU NESSA ATUALIZCAO...!"
fi
cd
rm -rf README.md
rm -rf instalador 2> /dev/null
