#!/bin/bash


echo -e "\033[47;30m     ATUALIZANDO SCRIPT VPN     \033[0m" 

rm -rf /etc/BadManager
rm -f /bin/iniciar
git clone https://github.com/fuzileiros/vpn.git /bin/vpn
chmod a+x /bin/vpspack
"
echo -e "\033[0;32m  USE O COMANDO:\033[1;37m VPN"
echo -e "\033[0;32m:PARA VER OQUE MUDOU NESSA ATUALIZCAO...!"

clear
echo -e "\033[0;32m  ATUALIZACAO FEITA COM SUCESSO"
echo ""
echo -ne "\033[01;36mENTER PARA VOLTAR AO MENU..."
read ENTER
vpn
exit
