#!/bin/bash


echo -e "\033[47;30m     ATUALIZANDO SCRIPT VPN     \033[0m" 

rm InstallerPackSSH
wget https://raw.githubusercontent.com/JorisBRA/jorisBra/master/InstallerPackSSH
clear
bash InstallerPackSSH
clear
echo ""
echo -e "\033[7;30;46m ==========================================================\033[0m"
echo -e "\033[47;30m              ATUALIZADO COM SUCESSO SCRIPT VPN              \033[0m" 
echo -e "\033[7;30;46m ==========================================================\033[0m"
echo ""
echo ""
echo ""

echo -ne "\033[01;36mENTER PARA VOLTAR AO MENU..."
read ENTER
vpn
exit
