#!/bin/bash

clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' "BANNER SSH" ; tput sgr0
echo ""
sleep 0.2
echo "        Edited @ColtSeals"
sleep 0.3
echo "        NERDOLOGIA VPS"
sleep 0.4
echo "        NETFREE: FOREVER"
sleep 0.2
echo "        Nome: MenuVPS 1.0"
echo ""
sleep 0.3
clear
sshd_config_bak=$(cat /etc/ssh/sshd_config |grep -v "Banner")
echo "$sshd_config_bak" > /etc/ssh/sshd_config
echo "Banner /etc/bannerssh" >> /etc/ssh/sshd_config
service ssh restart 1>/dev/null 2>/dev/null
service sshd restart 1>/dev/null 2>/dev/null
if [ -f /etc/bannerssh ]
then
banner=$(cat /etc/bannerssh)
else
banner="Não há um banner no momento"
fi
echo -e "\033[1;32mBanner atual\n\n\033[1;37m$banner\n\033[0m"
echo "Qual banner deseja adicionar (ctrl + c para sair )"
read -p ": " bannerssh
echo "$bannerssh" > /etc/bannerssh
service ssh restart 1> /dev/null 2>/dev/null
service sshd restart 1>/dev/null 2>/dev/null

echo -e "\033[1;30m  BANNER SSH aplicado com sucesso!\033[0m"
echo ""
echo -e "\033[1;30m  NÃO DEIXE DE ENTRAR NO NOSSO GRUPO & NO CANAL NERDs\033[0m"
