#!/bin/bash
# --------------------------------------
# ./cor.sh
#
# Script para imprimir cores em Shell Script (Bash)
#
# Uso:  ./cor.sh 'Texto' [cor] [ atributo]
#
# Ex.:  ./cor.sh 'Texto'
#    ./cor.sh 'Texto' amarelo
#    ./cor.sh 'Texto' amarelo negrito
#
# Observações:
#
#   1 - use o Texto somente entre aspas ''
#   2 - use a ordem: [1° texto] [2° cor] [3° atributo]
# 3 - se você não informar a cor, será branca
# 4 - se você não informar o atributo, será normal
#   5 - use o nome das cores (vermelho, verde, amarelo, azul, rosa, branco e preto), ou em inglês
#   6 - use os atributos (normal ou nor, negrito ou neg, sublinhado ou sub e reverso ou rev)
#
# Autor: Marcos da B. M. Oliveira , www.terminalroot.com.br
# Desde: Qui 03 Out 2013 21:56:14 BRT 
# Licença: GPL
# --------------------------------------
##############--COR--###############
if [ "$2" ]; then
 case "$2" in
  vermelho | red)
   cor="31m"
  ;;
  verde | green)
   cor="32m"
  ;;
  amarelo | yellow)
   cor="33m"
  ;;
  azul | blue)
   cor="34m"
  ;;
  rosa | pink)
   cor="35m"
  ;;
  cinza | gray)
   cor="36m"
  ;;
  branco | white)
   cor="37m"
  ;;
  preto | black)
   cor="30m"
  ;;
  *)
   cor="37m"
  ;;
 esac
else
  cor="37m";
fi
  
##############--ATRIBUTO--###############
if [ "$3" ]; then
 case "$3" in
  normal | nor)
   atributo="0"
  ;;
  negrito | neg | bold)
   atributo="1"
  ;;
  sublinhado | sub | underline)
   atributo="4"
  ;;
  reverso | rev)
   atributo="7"
  ;;
 esac
else
  atributo="0";
fi
##############--TEXTO--###############
texto="$1"
echo -e "\033[$atributo;$cor$texto\033[0m"
