#!/bin/bash

clear
echo -e "\033[1;31mAguarde, coletando informações....\033[0m"
sleep 3
clear
cat /proc/cpuinfo
echo -e "\033[1;36mPressione \033[1;31mENTER \033[1;36mpara voltar ao menu anterior.\033[0m"
read  #enter
1