#!/bin/bash

clear
echo "Edited by @ColtSeals"
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Conectando ao NerdologiaVPS..."
sleep 0.4
echo "Checando Permissão..."
sleep 0.2
echo -e "${green}Permissão Aceita...${NC}"
sleep 0.2
clear
echo -e "\033[1;31mAguarde, coletando informações....\033[0m"
sleep 3
clear
cat /proc/cpuinfo
echo -e "\033[1;36mPressione \033[1;31mENTER \033[1;36mpara voltar ao menu anterior.\033[0m"
read  #enter
hardware
