#!/bin/bash
clear
echo "Edited by @ColtSeals"
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Conectando ao NerdologiaVPS..."
sleep 0.4
echo "Checando Permissão..."
sleep 0.2
echo -e "${green}Permissão Aceita...${NC}"
sleep 0.2
clear
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"
echo -e "\033[1;30m------------------------------------ENTREM--------------------------------\033[0m"
echo -e "\033[1;30m--------------------------------------------------------------------------\033[0m"
echo -e "\033[1;37m     _/      _/       _/_/_/_/       _/_/_/        _/_/_/          _/_/_/ \033[0m"
echo -e "\033[1;37m    _/_/    _/       _/             _/    _/      _/    _/      _/        \033[0m"  
echo -e "\033[1;37m   _/  _/  _/       _/_/_/         _/_/_/        _/    _/        _/_/     \033[0m"
echo -e "\033[1;37m  _/    _/_/       _/             _/    _/      _/    _/            _/    \033[0m"
echo -e "\033[1;37m _/      _/       _/_/_/_/       _/    _/      _/_/_/        _/_/_/       \033[0m"
echo -e "\033[1;37m--------------------------------------------------------------------------\033[0m"
echo -e "\033[0;36m        Telegram Channels Oficiais @VpsNerdologia & @ColtChannel\033[0m"
echo -e "\033[1;30m--------------------------------------------------------------------------\033[0m"
echo -e "\033[1;37mENTREM NOS Channels & no Grupo onde você irá encontrar o melhor Contéudo\033[0m"
echo -e "\033[1;30m--------------------------------------------------------------------------\033[0m" 
echo -e "\033[1;30m--------------------------------------------------------------------------\033[0m"
echo -e "\033[1;34mSou Louco por TecnologY e sempre disposto a ajudar quem merece ser ajudado\033[0m"
echo -e "\033[1;30m--------------------------------------------------------------------------\033[0m"
echo -e "\033[1;33m Script foi editado por mim com todas as ferramentas que acho necessário  \033[0m"  
echo -e "\033[1;30m--------------------------------------------------------------------------\033[0m"
echo -e "\033[1;30m               Script Edited ColtSeals TecnologY (NERD's)                 \033[0m"
echo -e "\033[1;30m--------------------------------------------------------------------------\033[0m"
echo -e "\033[1;30m       A Internet aproxima quem está longe e afasta quem está perto!      \033[0m"
echo -e "\033[1;30m--------------------------------------------------------------------------\033[0m"
echo -e "\033[1;30m                   TELEGRAM CANAL: @VpsNerdologia                         \033[0m"
echo -e "\033[1;30m--------------------------------------------------------------------------\033[0m"
echo -e "\033[1;30m                   TELEGRAM CANAL: @ColtChannel                           \033[0m"
echo -e "\033[1;30m--------------------------------------------------------------------------\033[0m"
echo -e "\033[1;30m                   TELEGRAM GRUPO: @NerdologiaVps                         \033[0m"
echo -e "\033[1;30m--------------------------------------------------------------------------\033[0m"
echo -e "\033[1;33m       ♛Copyright © 2017 aos NERDs Script Edited By @ColtSeals♛         \033[0m"  
echo -e "\033[1;30m--------------------------------------------------------------------------\033[0m"
echo ""
echo -ne "\033[01;36mENTER PARA VOLTAR AO MENU..."
read ENTER
vpspack
exit
