#!/bin/bash

clear
while true; do
echo -e "\033[1;34m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;34m               a88888b.  .88888.  dP        d888888P                  \033[0m"
echo -e "\033[1;34m              d8'   `88 d8'   `8b 88           88                     \033[0m"
echo -e "\033[1;34m              88        88     88 88           88                     \033[0m"
echo -e "\033[1;34m              88        88     88 88           88                     \033[0m"
echo -e "\033[1;34m              Y8.   .88 Y8.   .8P 88           88                     \033[0m"
echo -e "\033[1;34m               Y88888P'  `8888P'  88888888P    dP                     \033[0m"
echo -e "\033[1;34m            ooooooooooooooooooooooooooooooooooooooo                   \033[0m"

echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;30m•••••> Script Edited ColtSeals TecnologY (NERD's)\033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;34m•••••> Script Edited ••ColtSeals TecnologY••\033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;30m•••••> A Internet aproxima quem está longe e afasta quem está perto!\033[0m"
echo -e "\033[1;30m•••••> TELEGRAM CANAL: @VpsNerdologia\033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;30m•••••> TELEGRAM CANAL: @ColtChannel\033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;30m•••••> TELEGRAM GRUPO: @NerdologiaVps\033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
done
sleep 6s
clear
done
