#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"
clear
while true; do
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;30m                a88888b.  .88888.  dP        d888888P      \033[0m"
echo -e "\033[1;30m               d8'   `88 d8'   `8b 88           88           \033[0m"
echo -e "\033[1;30m               88        88     88 88           88             \033[0m"
echo -e "\033[1;30m               88        88     88 88           88            \033[0m"
echo -e "\033[1;30m               Y8.   .88 Y8.   .8P 88           88              \033[0m"
echo -e "\033[1;30m                Y88888P'  `8888P'  88888888P    dP            \033[0m"
echo -e "\033[1;30m              ooooooooooooooooooooooooooooooooooooooo         \033[0m"

echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;30m•••••> Script Edited ColtSeals TecnologY (NERD's)\033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;34m•••••> Script Edited ••ColtSeals TecnologY••\033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;30m•••••> A Internet aproxima quem está longe e afasta quem está perto!\033[0m"
echo -e "\033[1;30m•••••> TELEGRAM CANAL: @VpsNerdologia\033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;30m•••••> TELEGRAM CANAL: @ColtChannel\033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
echo -e "\033[1;30m•••••> TELEGRAM GRUPO: @NerdologiaVps\033[0m"
echo -e "\033[1;30m----------------------------------------------------------------------\033[0m"
done
sleep 6s
clear
done
