#!/bin/bash
echo "Criar Usuários"
echo ""
echo "        BY: @ColtSeals"
echo "        Menu VPS"
echo "        NerdologiaVPS"
echo "        Nome: MenuVPS 1.0"
echo ""
read -p "De enter para continuar..."
clear
tput setaf 8 ; tput setab 5; tput bold ; printf '%30s%s%-15s\n' "Criar Usuário SSH" ; tput sgr0
echo ""
