#!/bin/bash
clear
echo "Edited by @ColtSeals"
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Conectando ao NerdologiaVPS..."
sleep 0.4
echo "Checando Permissão..."
sleep 0.2
echo -e "${green}Permissão Aceita...${NC}"
sleep 0.2
clear
mkdir /etc/usuariosteste 1>/dev/null 2>/dev/null
echo -e "   Usuarios teste"
for testus in $(ls /etc/usuariosteste |sort |sed 's/.sh//g')
do
echo "$testus"
done
printf "\n"
printf "Nome do novo usuario: "; read nome
printf "Senha do usuario: "; read pass
echo -e "\nUse s = segundos, m = minutos, h = horas e d = dias EX: 14s ."
printf "Quanto tempo usuario $nome deve durar: ";read tempoin
tempo=$(echo "$tempoin" |sed 's/ //g')
useradd -M -s /bin/false $nome
(echo $pass;echo $pass) |passwd $nome 1>/dev/null 2>/dev/null
echo "#!/bin/bash
sleep $tempo
kill"' $(ps -u '"$nome |awk '{print"' $1'"}') 1>/dev/null 2>/dev/null
userdel --force $nome
rm -rf /etc/usuariosteste/$nome.sh
exit" > /etc/usuariosteste/$nome.sh
		MYIP=$(wget -qO- ipv4.icanhazip.com)
		clear
echo "Connectando ao @NerdologiaVPS..."
sleep 0.4
echo "Criando Conta..."
sleep 0.3
echo "Gerando Host..."
sleep 0.2
echo "Criando seu usuario TESTE: $username"
sleep 0.2
echo "Criando senha para $username"
sleep 0.2

  clear
  echo "Script Edited @ColtSeals"
  echo "Informações @NerdologiaVPS"
  echo " "
  echo "   Detalhes do Usuario teste"
  echo "-----------------------------------------------"
  echo "   Host            : $MYIP"
  echo "   Nome            : $nome"
  echo "   Senha           : $pass"
  echo "   Validade        : $tempo"
  echo "   Porta           : 80,8080,8799,443,22,3128"
  echo "----------------------------------------------"
  echo " "
echo -e "Apos o tempo expirar o usuario sera deletado e todos serão desconectados."
bash /etc/usuariosteste/$nome.sh &
echo ""
echo -ne "\033[01;36mENTER PARA VOLTAR AO MENU..."
read ENTER
vpspack
exit
