#!/bin/bash
clear
echo "Edited by @ColtSeals"
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Conectando ao NerdologiaVPS..."
sleep 0.4
echo "Checando Permissão..."
sleep 0.2
echo -e "${green}Permissão Aceita...${NC}"
sleep 0.2
clear

MYIP=$(wget -qO- ipv4.icanhazip.com)

cat /etc/passwd |grep ovpn > /tmp/ovpn
echo -e "\033[1;33mUSUARIOS"
SDK=$(awk -F: '{print $1}' /tmp/ovpn)
if [ "$SDK" = "" ]
then
echo -e "\033[1;31mVOCE NAO TEM USUARIOS PARA MUDAR A DATA!\033[0m"
echo ""
echo -ne "\033[01;36mENTER PARA VOLTAR AO MENU ANTERIOR..."
read ENTER
gerenciaropen
exit
 else
echo -e "\033[1;31m_____________________________"
awk -F: '{print $1}' /tmp/ovpn
echo -e "\033[1;31m_____________________________"
echo -e "\033[1;36mNOME DO USUARIO\033[0m"
read -p ": " namer
echo -e "\033[1;36mDIGITE A NOVA DATA EM NUMEROS\033[0m"
echo -e "\033[1;36mDIA?\033[0m"
read -p ": " dia
echo -e "\033[1;36mMES?\033[0m"
read -p ": " mes
echo -e "\033[1;36mANO?\033[0m"
read -p ": " ano
date="$dia/$mes/$ano"
chage -E $date $namer 2> /dev/null

  echo "   Data alterada com Sucesso"
  echo "-----------------------------------------------"
  echo "   Host            : $MYIP"
  echo "   Nome            : $namer"
  echo "   Data Expiração  : $datexp"
  echo "----------------------------------------------"
echo ""
echo -ne "\033[01;36mENTER PARA VOLTAR AO MENU ANTERIOR..."
read ENTER
gerenciaropen
exit
