#!/bin/bash
clear

echo -e "\033[7;30;46m ==========================================================\033[0m"
echo -e " \033[7;30;46m\033[5;37;40m                   VPN DROPBEAR                    \033[0m"
echo -e "\033[7;30;46m ==========================================================\033[0m"

#!/bin/bash
if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Voce não é root"
	echo "Seu usuario esta no grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	exit
	else
	clear
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	exit
	fi
fi

verdee="\033[1;32m"
amareloo="\033[1;33m"
fi="\033[0m"

maisporta () {
echo -e "\033[1;34m________________________________________\033[0m"
echo -e "\033[1;31mDIGITE QUAL PORTA DESEJA USAR... 
80,320,1150,3128,8080,8090...\033[0m"
read -p "PORTA: " pt
if [ "$pt" = "22" ]
then
echo -e "\033[1;31mPORTA 22 DESTINADA A GERENCIAMENTO DA VPS\033[0m"
funcao
echo -e "\033[1;34m________________________________________\033[0m"
else
if [ "$pt" = "443" ]
then
echo -e "\033[1;31mPORTA 443 DESTINADA A GERENCIAMENTO DA VPS\033[0m"
funcao
echo -e "\033[1;34m________________________________________\033[0m"
else
sed -i "s/443/$pt -p 443/g" /etc/default/dropbear
echo -e "\033[7;31m\033[7;41m"
for prog in $(seq 13);
do
echo -n "||"
sleep 0.1s
echo -n "|"
sleep 0.1s
done
echo ""
sleep 1s
echo -e "\033[0m\033[1;32m
Porta $pt Foi Adicionada ao DropBear! $fi"
echo -e "\033[1;34m________________________________________\033[0m"
echo -e ""
echo "$pt" >> /tmp/portas
funcao
sleep 1s
 fi
fi
}

funcao () {
echo -e "\033[1;31mDESEJA ABRIR MAIS PORTAS PARA O DROPBEAR?\033[0m"
read -p "[s/n]: " apr
if [ "$apr" = "s" ]
then
maisporta
else
echo -e "\033[1;31mContinuando...\033[0m"
fi
sleep 1s
}
#####FimdasPortas###
touch /tmp/portas
echo -e "\033[1;31m[1] VAI USAR DROPBEAR PARA UMA CONEXAO DIRETA SEM PROXY SQUID?
[2] OU VAI USAR COM SQUID NORMALMENTE?
DIGITE \033[0m"
echo -e "\033[1;31m[1/2]\033[0m"
read -p "OPCAO: " -e -i 1 opcao
case $opcao in
 1)
drop="2"
squidinstall="n"
echo -e "/bin/false" >> /etc/shells
;;
2)
drop="2"
squidinstall="s"
echo -e "/bin/false" >> /etc/shells
;;
*)
echo -e "\033[1;31mVoce não escolheu uma opção, por padrão sera instalado, Sem PROXY\033[0m"
drop="2"
squidinstall="n"
echo -e "/bin/false" >> /etc/shells
;;
esac
echo -e "\033[1;33mINSTALACAO PADRAO OU PERSONALIZADA?"
read -p "[1] - PADRAO
[2] - PERSONALIZADA
: " padr
echo -e "\033[0m"
case $padr in
1)
insta="1"
;;
2)
insta="2"
;;
*)
insta="1"
;;
esac
#INSTALACAO#
if [ "$drop" = "2" ]
then
echo -e "\033[1;31mDIGITE QUAL PORTA PRINCIPAL DESEJA USAR, 443 JA VEM ABERTA! 80,320,3128,8080...\033[0m"
read -p "PORTA: " -e -i 80 pts
if [ "$pts" = "" ]; then
porta="80"
else
 if [ "$pts" = "22" ]; then
echo -e "\033[1;31mPORTA 22 DESTINADA A GERENCIAMENTO DA VPS\033[0m"
 else
   if [ "$pts" = "443" ]; then
echo -e "\033[1;31mPORTA 443 JA VEM ABERTA!\033[0m"
porta="80"
 else
porta="$pts"
    fi
  fi
fi
echo "$porta" >> /tmp/portas
echo "443" >> /tmp/portas
echo -e "$verdee
QUAL A VERSAO DA SUA VPS?$corPadrao"
echo -e "$amareloo [1] Debian
 [2] Ubuntu
 [0] Sair $corPadrao"
read -p "OPCAO: " option4
case $option4 in
1)
opcao4="1"
;;
2)
opcao4="2"
;;
0)
opcao4="3"
;;
*)
opcao4="3"
;;
esac
sleep 2s
fi
if [ "$opcao4" = "1" ]
then
echo "Port 22
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes" > /etc/ssh/sshd_config
service ssh restart 1>/dev/null 2>/dev/null
echo "Instalando dropbear"
apt-get install dropbear -y 1>/dev/null 2>/dev/null
touch /etc/dropbear/banner
sleep 2s
echo "Configurando dropbear"
printf "#loading\nNO_START=0\nDROPBEAR_PORT=$porta\n" > /etc/default/dropbear
echo -e 'DROPBEAR_EXTRA_ARGS="-p 443"' >> /etc/default/dropbear
sleep 2s
echo "Seu dropbear foi configurado com sucesso"
sleep 2s
echo -e "$verdee"
  if [[ "$squidinstall" = 's' ]]; then
sleep 2s
echo -e "\033[0m"
    if [ "$insta" = "2" ]; then
echo -e "\033[1;31mDESEJA ABRIR MAIS PORTAS PARA O DROPBEAR?\033[0m"
read -p "[s/n] " -e -i n abrir
      if [ "$abrir" = "s" ]
then
maisporta
      fi
     fi
echo -e "\033[1;33mIniciando Instalaçao Squid\033[0m"
sleep 3s
SQUID3IS
echo -e "$verdee
AGORA SO USAR O COMANDO ADM
E TESTAR O FUNCIONAMENTO DO METODO
VOCE CONFIGUROU ELE NAS PORTAS\033[1;31m"
cat /tmp/portas
rm -rf /tmp/portas
echo -e "\033[0m"
sleep 5s
echo 'DROPBEAR_BANNER="/etc/dropbear/banner"
DROPBEAR_RECEIVE_WINDOW=65536' >> /etc/default/dropbear
echo "Saindo..."
sleep 2s
service ssh restart 1>/dev/null 2>/dev/null
service dropbear restart 1>/dev/null 2>/dev/null
exit
  else
     if [ "$insta" = "2" ]; then
echo -e "\033[1;31mDESEJA ABRIR MAIS PORTAS PARA O DROPBEAR?\033[0m"
read -p "[s/n] " -e -i n abrir
      if [ "$abrir" = "s" ]
then
maisporta
      fi
     fi
echo -e "$verdee
AGORA SO USAR O COMANDO ADM
E TESTAR O FUNCIONAMENTO DO METODO
VOCE CONFIGUROU ELE NAS PORTAS\033[1;31m"
cat /tmp/portas
rm -rf /tmp/portas
echo -e "\033[0m"
sleep 5s
echo 'DROPBEAR_BANNER="/etc/dropbear/banner"
DROPBEAR_RECEIVE_WINDOW=65536' >> /etc/default/dropbear
echo "Saindo..."
sleep 2s
service ssh restart 1>/dev/null 2>/dev/null
service dropbear restart 1>/dev/null 2>/dev/null
exit
  fi
fi

if [ "$opcao4" = "2" ]
then
echo "Port 22
Protocol 2
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes" > /etc/ssh/sshd_config
service ssh restart 1>/dev/null 2>/dev/null
echo "Instalando dropbear"
apt-get install dropbear -y 1>/dev/null 2>/dev/null
touch /etc/dropbear/banner
sleep 2s
echo "Configurando dropbear"
printf "#loading\nNO_START=0\nDROPBEAR_PORT=$porta\n" > /etc/default/dropbear
echo -e 'DROPBEAR_EXTRA_ARGS="-p 443"' >> /etc/default/dropbear
sleep 2s
echo "Seu dropbear foi configurado com sucesso"
sleep 2s
echo -e "$verdee"
  if [[ "$squidinstall" = 's' ]]; then
    if [ "$insta" = "2" ]; then
echo -e "\033[1;31mDESEJA ABRIR MAIS PORTAS PARA O DROPBEAR?\033[0m"
read -p "[s/n] " -e -i n abrir
     if [ "$abrir" = "s" ]
then
maisporta
     fi
    fi
echo -e "\033[1;33mIniciando Instalaçao Squid\033[0m"
sleep 3s
SQUID3IS
echo -e "$verdee
AGORA SO USAR O COMANDO ADM
E TESTAR O FUNCIONAMENTO DO METODO
VOCE CONFIGUROU ELE NAS PORTAS\033[1;31m"
cat /tmp/portas
rm -rf /tmp/portas
echo -e "\033[0m"
sleep 5s
echo 'DROPBEAR_BANNER="/etc/dropbear/banner"
DROPBEAR_RECEIVE_WINDOW=65536' >> /etc/default/dropbear,
echo "Saindo..."
sleep 2s
service ssh restart 1>/dev/null 2>/dev/null
service dropbear restart 1>/dev/null 2>/dev/null
exit
  else
    if [ "$insta" = "2" ]; then
echo -e "\033[1;31mDESEJA ABRIR MAIS PORTAS PARA O DROPBEAR?\033[0m"
read -p "[s/n] " -e -i n abrir
     if [ "$abrir" = "s" ]
then
maisporta
     fi
    fi
echo -e "$verdee
AGORA SO USAR O COMANDO ADM
E TESTAR O FUNCIONAMENTO DO METODO
VOCE CONFIGUROU ELE NAS PORTAS\033[1;31m"
cat /tmp/portas
rm -rf /tmp/portas
echo -e "\033[0m"
sleep 5s
echo 'DROPBEAR_BANNER="/etc/dropbear/banner"
DROPBEAR_RECEIVE_WINDOW=65536' >> /etc/default/dropbear
echo "Saindo..."
sleep 2s
service ssh restart 1>/dev/null 2>/dev/null
service dropbear restart 1>/dev/null 2>/dev/null
exit
  fi
fi

if [ "$opcao4" = "3" ]
then
echo " Saindo... "
sleep 2s
exit
fi
