#!/bin/bash
###cores
verm="\033[1;31m"
verd="\033[1;32m"
ama="\033[1;33m"
azu="\033[1;34m"
fi="\033[0m"
###cores
clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' "ADICIONAR HOSTS EM (etc/hosts)&(etc/payloads)" ; tput sgr0
echo ""
echo "        Created @ColtSeals"
echo "        NERDOLOGIA VPS"
echo "        NETFREE: FOREVER"
echo "        Nome: MenuVPS 1.0"
echo ""
read -p "De enter para continuar..."
clear

ip=127.0.0.1
echo ""
echo "  Qual host deseja adicionar ?"
echo -e "\033[1;37m •=============================•\033[0m"
read -p ": " host
echo "$ip $host" >> /etc/hosts
echo "$host" >> /etc/payloads
chmod a+x /etc/hosts
echo ""
echo -ne "\033[01;36mENTER PARA VOLTAR AO MENU..."
read ENTER
vpspack
exit
