#!/bin/bash

CAMINHO_HOSTS="/etc/hosts"

echo "Entre com o novo ip"
read 127.0.0.1
echo "Entre com o nome da máquina"
read Host_Novo

echo "" > $CAMINHO_HOSTS
sed "10i $127.0.0.1        $Host_Novo" $CAMINHO_HOSTS -i
sed "10i \ " $CAMINHO_HOSTS -i
