#!/bin/bash
clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' "Resetar Firewall" ; tput sgr0
echo ""
echo "        Edited @ColtSeals"
echo "        NERDOLOGIA VPS"
echo "        NETFREE: FOREVER"
echo "        Nome: MenuVPS 1.0"
echo ""
read -p "De enter para continuar..."
clear
iptables -F
iptables -X
iptables -t mangle -F
iptables -t mangle -X
iptables -t nat -F
iptables -t nat -X
iptables -t filter -F
iptables -t filter -X
echo "Regras resetadas com sucesso!"
echo ""
echo -ne "\033[01;36mENTER PARA VOLTAR AO MENU..."
read ENTER
vpspack
exit
