#!/bin/bash

ip=$(wget -qO- ipv4.icanhazip.com)
clear
if [[ $1 == "" ]]
then
dia=$(date | awk {'print $3'})
mes=$(date | awk {'print $2'})
ano=$(date | awk {'print $6'})
if [[ "$mes" = "Jan" || "$mes" = "Jan" ]]; then
mes=01
elif [[ "$mes" = "Feb" || "$mes" = "Fev" ]]; then
mes=02
elif [[ "$mes" = "Mar" || "$mes" = "Mar" ]]; then
mes=03
elif [[ "$mes" = "Apr" || "$mes" = "Abr" ]]; then
mes=04
elif [[ "$mes" = "May" || "$mes" = "Mai" ]]; then
mes=05
elif [[ "$mes" = "Jun" || "$mes" = "Jun" ]]; then
mes=06
elif [[ "$mes" = "Jul" || "$mes" = "Jul" ]]; then
mes=07
elif [[ "$mes" = "Ago" || "$mes" = "Ago" ]]; then
mes=08
elif [[ "$mes" = "Set" || "$mes" = "Sep" ]]; then
mes=09
elif [[ "$mes" = "Out" || "$mes" = "Oct" ]]; then
mes=10
elif [[ "$mes" = "Nov" || "$mes" = "Nov" ]]; then
mes=11
elif [[ "$mes" = "Dec" || "$mes" = "Dez" ]]; then
mes=12
fi
echo -e "\033[5;36;40m ==========================================================\033[0m"
echo -e "\033[7;30;47m  DATA:\033[0m\033[7;30;41m $dia/$mes/$ano\033[0m"
echo -e "\033[7;30;47m  IP da VPS:\033[0m\033[7;30;41m $ip\033[0m"
system=$(cat /etc/issue.net)
if [ "$system" ]
then
echo -e "\033[7;30;47m  Sistema Operacional:\033[0m\033[7;30;41m $system\033[0m"
else
echo -e "\033[7;30;47m  Sistema Operacional:\033[0m\033[7;30;41mNot Available\033[0m"
fi
echo -e "\033[5;36;40m ==========================================================\033[0m"
echo -e "\033[7;30;47m  ®Script\033[0m \033[7;30;41mEdited:\033[0m \033[0m \033[0;36;40m@Colt\033[5;37;40mSeals\033[0m"
echo -e "\033[7;30;47m  ®TELEGRAM\033[0m \033[7;30;41mCANAL:\033[0m \033[0m \033[0;36;40m@Vps\033[5;37;40mNerdologia\033[0m"
echo -e "\033[5;36;40m ==========================================================\033[0m"
echo -e "\033[7;30;46m  Para Acessar este menu Principal:\033[5;37;40m VPN \033[0m"
echo -e "\033[5;36;40m ==========================================================\033[0m"
echo -e "\033[7;30;46m  Para Acessar este menu digite:\033[5;37;40m Ferramentas \033[0m"
echo -e "\033[5;36;40m ==========================================================\033[0m"

echo -e "\033[01;36m║\033[1;37m00\033[1;36m║\033[5;31;40m•\033[0m\033[0;31;40m SAIR \033[5;31;40m=\033[0m \033[1;30;41m Sair do Menu VPN. \033[0m"
echo -e "\033[01;36m║\033[1;37m01\033[1;36m║\033[5;31;40m•\033[0m\033[01;37m BACKUP USUARIOS \033[5;31;40m=\033[0m \033[7;36;40m Backup dos usuarios \033[0m"
echo -e "\033[01;36m║\033[1;37m02\033[1;36m║\033[5;31;40m•\033[0m\033[01;37m RESTAURAR USUÁRIOS \033[5;31;40m=\033[0m \033[7;36;40m Restaurar usuarios feito backup \033[0m"
echo -e "\033[01;36m║\033[1;37m03\033[1;36m║\033[5;31;40m•\033[0m\033[01;37m SPEED TEST \033[5;31;40m=\033[0m \033[7;36;40m Teste de conexão velocidade de banda \033[0m"
echo -e "\033[01;36m║\033[1;37m04\033[1;36m║\033[5;31;40m•\033[0m\033[01;37m FIREWALL BLOCK  \033[5;31;40m=\033[0m \033[7;36;40m bloquear torrent, icmp \033[5;31m RISCOS \033[0m"
echo -e "\033[01;36m║\033[1;37m05\033[1;36m║\033[5;31;40m•\033[0m\033[01;37m RESET FIREWALL \033[5;31;40m=\033[0m \033[7;36;40m Resetar regras iptables \033[0m"
echo -e "\033[01;36m║\033[1;37m06\033[1;36m║\033[5;31;40m•\033[0m\033[01;37m VOLTAR \033[5;31;40m=\033[0m \033[7;36;40m Voltar ao Menu Principal \033[0m"
echo -e "\033[5;36;40m ===========================================================\033[0m"
echo -e "\033[5;31;40m    •\033[0m\033[01;37m Digite uma Opção:\033[0;37m"; read -p " " opcao
else
opcao=$1
fi
case $opcao in
  0 | 00 )
   exit;;
  1 | 01 )
   backupusuarios;;
  2 | 02 )
   restaurarusuarios;;
  3 | 03 )
   clear
   speedtest --share;;
  4 | 04 )
   firewalblock;;
  5 | 05 )
   resetfirewal;;
  6 | 06 )
   vpn;;
esac
