#!/bin/bash
rm serverbase.elf > /dev/null 2>&1
IP=$(wget -qO- ipv4.icanhazip.com)
rm -rf /usr/lib/greenview
mkdir /usr/lib/greenview
read -p "Em qual porta você irá executar? (8080 recomendada) " -e -i 8080 PORTA
read -p "Qual senha deseja colocar? (padrão: velocidade) " -e -i velocidade SENHA
echo "Iniciando..."
cd /usr/lib/greenview
wget http://kanprojects.zapto.org/vpsmanager/conf/corebase.py -O corebase.py > /dev/null 2>&1
sed "s/IPVAIAQUI/$IP:$PORTA/" corebase.py > /tmp/coreb
sed "s/SENHAVAIAQUI/$SENHA/" /tmp/coreb > /tmp/coreb2
rm /tmp/coreb > /dev/null 2>&1
mv /tmp/coreb2 /usr/lib/greenview/corebase.py > /dev/null 2>&1
wget http://kanprojects.zapto.org/vpsmanager/conf/initsr -O /etc/init.d/96initsr > /dev/null 2>&1
chmod 777 /etc/init.d/96initsr
apt-get update > /dev/null 2>&1
apt-get install gcc-7 -y > /dev/null 2>&1
apt-get install g++ -y > /dev/null 2>&1
apt-get install libpython2.7 -y > /dev/null 2>&1
echo -e "\e[1;104;37m __________________________________________ \e[0m"
echo -e "\e[1;104;37m |Configurando arquivos...                | \e[0m"
echo -e "\e[1;104;37m |Isso vai levar entre 1 e 10 minutos.    | \e[0m"
echo -e "\e[1;104;37m |Caso pareça travado, aperte enter.      | \e[0m"
echo -e "\e[1;104;37m |Se pular uma linha, está só demorando.  | \e[0m"
echo -e "\e[1;104;37m |Caso contrário, travou.                 | \e[0m"
echo -e "\e[1;104;37m |Entre em contato comigo para solucionar.| \e[0m"
echo -e "\e[1;104;37m ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯ \e[0m"
