#!/bin/bash
clear
echo "Edited by @ColtSeals"
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Conectando ao NerdologiaVPS..."
sleep 0.4
echo "Checando Permissão..."
sleep 0.2
echo -e "${green}Permissão Aceita...${NC}"
sleep 0.2
clear
echo " "
echo -e "\033[1;30m•••••> Script Edited ColtSeals TecnologY (NERD's)\033[0m"
echo -e "\033[1;30m•••••> A Internet aproxima quem está longe e afasta quem está perto!\033[0m"
echo -e "\033[1;30m•••••> TELEGRAM CANAL: @VpsNerdologia\033[0m"
echo -e "\033[1;30m•••••> TELEGRAM CANAL: @ColtChannel\033[0m"
echo -e "\033[1;30m•••••> TELEGRAM GRUPO: @NerdologiaVps\033[0m"
echo -e "\033[1;37mPara executar um comando escolha uma das opçoẽs abaixo.\033[0m"
echo -e "\033[01;36m╠ \033[1;37m01\033[1;36m╣\033[01;37m CPU \033[01;32m(Detalhes sobre a CPU desse servidor)\033[0m"
echo -e "\033[01;36m╠ \033[1;37m02\033[1;36m╣\033[01;37m HD \033[01;32m(Detalhes sobre o HD desse servidor)\033[0m"
echo -e "\033[01;36m╠ \033[1;37m03\033[1;36m╣\033[01;37m Consumo RAM \033[01;32m(Detalhes do consumo RAM no servidor)\033[0m"
echo -e "\033[01;36m╠ \033[1;37m04\033[1;36m╣\033[01;37m Geral \033[01;32m(Todas as informações básicas gerais do servidor)\033[0m"
echo -e "\033[01;36m╠ \033[1;37m05\033[1;36m╣\033[01;37m Voltar \033[01;32m(Voltar para o MenuVPS)\033[0m"

read -p "Opção:" opcao

case $opcao in
  1 | 01 )
  cpu;;
  2 | 02 )
  HD;;
  3 | 03 )
  RAM;;
  4 | 04 )
  HardwareGeral;;
  5 | 05 )
  MenuVPS;;
  *)
  id > /dev/null 2> /dev/null
esac
