#!/bin/bash
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' "CONFIGURAR SQUID3" ; tput sgr0
echo ""
echo "        Edited @ColtSeals"
echo "        NERDOLOGIA VPS"
echo "        NETFREE: FOREVER"
echo "        Nome: MenuVPS 1.0"
echo ""
read -p "De enter para continuar..."
clear 
echo -e "\033[1;31mAguarde, coletando informações.....\033[0m"
sleep 3
df -h
echo -e "\033[1;36mPressione \033[1;31mENTER \033[1;36mpara voltar ao menu anterior.\033[0m"
read  #enter
hardware
