#!/bin/bash


echo -e "MenuVPS HELP"

echo -e "\033[01;37mFerramenta \033[1;31mConfigurar Script:"
echo ""
echo "Essa ferramenta irá instalar o squid fundamental para o funcionamento e conexão."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mConfSquid"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"
echo ""
echo -e "\033[01;37mFerramenta \033[1;31mLimite:"
echo ""
echo "Essa ferramenta irá limitar o numero de conexões de usuarios que teve seu limite aplicado."
echo "Ao exceder o limite as conexões excedentes serao desconectados !!"
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mLimite"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"
echo ""
echo -e "\033[01;37mFerramenta \033[1;31mCriar Usuario:"
echo ""

echo "Essa ferramenta tem objetivo criar usuarios com senha e número limite de forma rápida e aplicando uma validade em dias."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mCriar"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"

echo -e "\033[01;37mFerramenta \033[1;31mRemover Expirados:"

echo "Essa ferramenta tem objetivo de remover de forma automatica todos os usuarios expirados trazendo praticidade ao Script."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mExpiradosDel"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"


echo -e "\033[01;37mFerramenta \033[1;31mFerramenta Criar Teste:"

echo "Essa ferramenta tem objetivo criar usuarios de teste aplicando uma validade em segundos, minutos, horas & dias."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mTeste"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"


echo -e "\033[01;37mFerramenta \033[1;31mFerramenta BadVpn:"

echo "Essa ferramenta instala o BadVpn permitindo a utilização de Chamadas de audio e videos e Jogos online entre outras funções."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mBadVpn"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"


echo -e "\033[01;37mFerramenta \033[1;31mFerramenta BadVpn Start:"

echo "Essa ferramenta Ativa o BadVpn permitindo a utilização de Chamadas de audio e videos e Jogos online entre outras funções."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mBadStart"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"


echo -e "\033[01;37mFerramenta \033[1;31mFerramenta BadVpn Stop:"

echo "Essa ferramenta Para o BadVpn bloqueando a utilização de Chamadas de audio e videos e Jogos online entre outras funções."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mBadStop"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"

echo -e "\033[01;37mFerramenta \033[1;31mFerramenta Remover Limite:"

echo "Essa ferramenta Remove o limite de conexões de um usuario desejado."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mLimiteDel"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"

echo -e "\033[01;37mFerramenta \033[1;31mFerramenta Mudar Nome:"

echo "Essa ferramenta tem o objetivo de mudar nome de um usuario."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mMudarNome"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"


echo -e "\033[01;37mFerramenta \033[1;31mRedefinir Usuario:"

echo "Essa ferramenta redefine o limite de logins de um usuario ou redefinir a data de expiração de um usuario."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mRedefinir"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"

echo -e "\033[01;37mFerramenta \033[1;31mDeletar Usuario:"

echo "Essa ferramenta tem função de deletar usuarios Forçar o deletamento e tambem desconectar todos de um usuario."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mUsuariosDel"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"


echo -e "\033[01;37mFerramenta \033[1;31mFirewall-Block: \033[1;31mRISCOS\033[1;30m])\033[1;33m""

echo "Essa ferramenta firewall-block faz o bloqueio torrent e protocolo icmp."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mFiBlock"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"


echo -e "\033[01;37mFerramenta \033[1;31mFirewall-Reset: \033[1;31mRISCOS\033[1;30m])\033[1;33m""

echo "Essa ferramenta Firewall-reset desfaz todas as regras iptables desabilitando qualquer bloqueio no firewall."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mFiReset"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"

echo "ATENÇAO ESSAS DUAS FERRAMENTAS PODEM CAUSAR PROBLEMAS EXECUTE POR SUA CONTA"
echo "MUITAS EMPRESAS USAM O IPTABLES EM SUAS MAQUINAS VIRTUAIS E ESSE NÃO PODE SER ALTERADO."


echo -e "\033[01;37mFerramenta \033[1;31mAdicionar Host:"

echo "Essa ferramenta add-hosts ela adiciona novos dominios (hosts payloads) em qualquer tipo de squid.conf."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mAddHost"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"


echo -e "\033[01;37mFerramenta \033[1;31mBackup Usuários:"

echo "Essa ferramenta Backup Usuarios realiza backup de todos os Usuarios criados e Senhas."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mBackup"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"


echo -e "\033[01;37mFerramenta \033[1;31mRestaurar Usuarios:"

echo "Essa ferramenta Restaura todos os Usuarios e Senhas de todos usuarios que foram feitos Backup."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mRestaurarBack"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"


echo -e "\033[01;37mFerramenta \033[1;31mDetalhes Usuarios:"

echo "Essa ferramenta de Informações de usuarios como usuario, senha, limite e data de expiração."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mDetalhes"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"


echo -e "\033[01;37mFerramenta \033[1;31mBanner SSH:"

echo "Essa ferramenta Para adicionar um Banner de Boas Vindas no servidor SSH."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mBanner"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"


echo -e "\033[01;37mFerramenta \033[1;31mSpeed Teste:"

echo "Essa ferramenta realiza um teste de Velocidade interno do Servidor Ping, Download & Upload."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mSpeed"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"

echo -e "\033[01;37mFerramenta \033[1;31mMenuVPS Help:"

echo "Essa ferramenta com Informações detalhadas sobre as funções do MenuVPS."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mAjuda"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"


echo -e "\033[01;37mFerramenta \033[1;31mDeletar Todos:"

echo "Essa ferramenta irá deletar todos os usuarios criados no Servidor."
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mDeletarTodos"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"


echo -e "\033[01;37mFerramenta \033[1;31mOpen VPN:"

echo "Essa ferramenta Instala, cria usuarios .ovpn  e gerenciar Usuarios .ovpn"
echo -e "\033[01;37mPara executar digite o comando: \033[1;31mOpenVPN"
echo -e "\033[1;37mOu execute pelo \033[1;32mMenuVPS"

echo "OUTROS:
echo "PARA RETIRAR O LIMITE DE CONEXOES DE UM USUARIO OU DE TODOS APAGUE"

echo "rm /etc/usuarios/usuario.sh"
echo "rm /etc/tempo/usuario.sh"

echo "Ou retire o limite de todos"

echo "rm -r /etc/tempo /etc/usuarios"


echo -e "\033[01;37m(Telegram Canal: \033[1;31m@VpsNerdologia)"
echo -e "\033[01;37m(Telegram Canal: \033[1;31m@ColtChannel)"
echo -e "\033[01;37m(Telegram Canal: \033[1;31m@NerdologiaVps)"
