#!/bin/bash
cd
if [ $(id -u) != 0 ]
then
echo "Execute o script como root"
exit
fi
echo -e "\033[1;30mInstalando...\033[0m"
mkdir /etc/VpsPackdir 2>/dev/null
mkdir /etc/VpsPackdir/limite 2>/dev/null
mkdir /etc/VpsPackdir/senha 2>/dev/null
rm -rf /bin/limite 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/limite > /bin/limite
chmod +x /bin/limite
rm -rf /bin/criarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/criarusuario > /bin/criarusuario
chmod +x /bin/criarusuario
rm -rf /bin/deletarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/deletarusuario > /bin/deletarusuario
chmod +x /bin/deletarusuario
rm -rf /bin/redefinirusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/redefinirusuario > /bin/redefinirusuario
chmod +x /bin/redefinirusuario
rm -rf /bin/vpspack 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/os > /bin/os
chmod +x /bin/os
rm -rf /bin/speedtest.py 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/speedtest.py > /bin/speedtest.py
chmod +x /bin/speedtest.py
wget https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/OpenVPN -O /bin/OpenVPN
chmod +x /bin/OpenVPN
sed -i -e 's/\r$//' /bin/OpenVPN
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/ConfSquid > /bin/ConfSquid
chmod +x /bin/ConfSquid
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/RemoverExpirados > /bin/RemoverExpirados
chmod +x /bin/ConfSquid
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/ConfSquid > /bin/ConfSquid
chmod +x /bin/RemoverExpirados
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Teste > /bin/Teste
chmod +x /bin/Teste
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/BadVpn.sh > /bin/BadVpn.sh
chmod +x /bin/BadVpn.sh
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Monitorar > /bin/Monitorar
chmod +x /bin/Monitorar
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/RemoverLimite > /bin/RemoverLimite
chmod +x /bin/RemoverLimite
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/MudarNome > /bin/MudarNome
chmod +x /bin/MudarNome
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/RedefinirUsuario > /bin/RedefinirUsuario
chmod +x /bin/RedefinirUsuario
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/DeletarUsuario > /bin/DeletarUsuario
chmod +x /bin/DeletarUsuario
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/FirewallBlock > /bin/FirewallBlock
chmod +x /bin/FirewallBlock
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/FirewallReset > /bin/FirewallReset
chmod +x /bin/FirewallReset
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/AddHost > /bin/AddHost
chmod +x /bin/AddHost
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/RemoverHost > /bin/RemoverHost
chmod +x /bin/RemoverHost
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Backup > /bin/Backup
chmod +x /bin/Backup
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Restaurar > /bin/Restaurar
chmod +x /bin/Restaurar
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/DetalhesUsuarios > /bin/DetalhesUsuarios
chmod +x /bin/DetalhesUsuarios
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Banner > /bin/Banner
chmod +x /bin/Banner
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/speedtest.py > /bin/speedtest.py
chmod +x /bin/speedtest.py
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/LimpadorCache > /bin/LimpadorCache
chmod +x /bin/LimpadorCache
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/VNC > /bin/VNC
chmod +x /bin/VNC
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/tcptweaker > /bin/tcptweaker
chmod +x /bin/tcptweaker
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/DeletarTodos > /bin/DeletarTodos
chmod +x /bin/DeletarTodos
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Ajuda > /bin/Ajuda
chmod +x /bin/Ajuda
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Telegram > /bin/Telegram
chmod +x /bin/Telegram
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/Desinstalar > /bin/Desinstalar
chmod +x /bin/Desinstalar
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/MenuVPS/master/SistemaDetalhes > /bin/SistemaDetalhes
chmod +x /bin/SistemaDetalhes

clear
echo -e "\033[1;31m•••••> \033[01;37mScript Edited ••ColtSeals TecnologY•• \033[0m"
echo -e "\033[1;32m•••••> A Internet aproxima quem está longe e afasta quem está perto!"
echo -e "\033[1;32m•••••> TELEGRAM GRUPO: @NerdologiaVps"
echo -e "\033[1;32m•••••> TELEGRAM CANAL: @VpsNerdologia"
echo -e "\033[1;32mInstalacao concluida\n\033[1;30mExecute:"
echo -e "\n\033[1;32mMenuVPS \033[1;30mMenu com opcoes"
echo -e "\033[1;32mcriarusuario \033[1;30mCriar usuario com data e limite"
echo -e "\033[1;32mdeletarusuario \033[1;30mDeletar usuario ou apenas desconectar"
echo -e "\033[1;32mredefinirusuario \033[1;30mAlterar data, senha, etc, de um usuario"
echo -e "\033[1;32mlimite \033[1;30mLimite de logins simultaneos\033[0m"
echo -e "\033[1;32mopen \033[1;30m(Configura e Gerencia Usuarios .ovpn)\033[0m"
rm -rf install
cp /bin/vpspack /bin/vps
cp /bin/vpspack /bin/MenuVPS
cp /bin/OpenVPN /bin/open
