#!/bin/bash
###cores
verm="\033[1;31m"
verd="\033[1;32m"
ama="\033[1;33m"
azu="\033[1;34m"
fi="\033[0m"
###cores
clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' "INSTALAR GET TUNNEL" ; tput sgr0
echo ""
echo "        Created @ColtSeals"
echo "        NERDOLOGIA VPS"
echo "        NETFREE: FOREVER"
echo "        Nome: MenuVPS 1.0"
echo ""
echo "Escolha uma porta que não esteja em USO..."
echo ""
read -p "APERTE ENTER PARA CONTINUAR..."
clear
IP=$(wget -qO- ipv4.icanhazip.com)
   echo ""
   echo ""
   echo "Em qual porta deseja Utilizar o Get Tunnel?"      
read -p "Porta do Get Tunnel: " -e -i 8080 PORTA

sed "s/fuzileiro/$IP:$PORTA/" /bin/get.py 

clear
   echo ""
   echo ""
  echo "Qual PASS deseja usar para o Get Tunnel?"
read -p "PASS do Get Tunnel:" SENHA

sed "s/naval/$SENHA/" /bin/get.py 

clear

echo "Iniciando..."
sleep 3
clear


   nohup python get.py > get.txt &
clear
   echo ""
clear
   echo -e "\033[7;30;46m ==========================================================\033[0m"
clear
   echo ""
clear
   echo ""
clear
   echo ""
clear
   echo ""
clear
   echo ""
clear
   echo ""
clear
   echo -e "\033[7;30;46m ==========================================================\033[0m"
   echo -e "\033[7;30;47m           Get Tunnel\033[0m \033[7;30;41mIniciado com SUCESSO\033[0m"
   echo -e "\033[7;30;46m ==========================================================\033[0m"
   echo ""
   echo -ne "\033[01;36m  ENTER PARA VOLTAR AO MENU..."
   read ENTER
   vpspack
   exit;;
