#!/bin/bash
cd
if [ $(id -u) != 0 ]
then
echo "Execute o script como root"
exit
fi
echo -e "\033[1;30mInstalando...\033[0m"
mkdir /etc/VpsPackdir 2>/dev/null
mkdir /etc/VpsPackdir/limite 2>/dev/null
mkdir /etc/VpsPackdir/senha 2>/dev/null

if [ ! -d "/home/DATABASE" ]; then
  mkdir /home/DATABASE; mkdir /home/DATABASE/Backups; touch /home/DATABASE/bannerssh.txt; touch /home/DATABASE/messages.txt; touch /home/DATABASE/users.db; awk -F : '$3 >= 500 { print $1 " **** 1" }' /etc/passwd | grep -v "nobody" | sort > /home/DATABASE/users.db
fi
#Menu Principal

rm -rf /bin/vpspack 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/vpn/master/vpspack > /bin/vpspack
chmod +x /bin/vpspack
#Fim do Menu Principal

rm -rf /bin/limite 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/vpn/master/limite > /bin/limite
chmod +x /bin/limite
#Fim Menu

#Menus Gerenciadores
#01
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/gerenciarusuarios -O /bin/gerenciarusuarios
chmod +x /bin/gerenciarusuarios
#02
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/gerenciarferramentas -O /bin/gerenciarferramentas
chmod +x /bin/gerenciarferramentas
#04
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/gerenciarsquid -O /bin/gerenciarsquid
chmod +x /bin/gerenciarsquid
#05
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/gerenciarsistema -O /bin/gerenciarsistema
chmod +x /bin/gerenciarsistema
#06
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/menuinstalacao -O /bin/menuinstalacao
chmod +x /bin/menuinstalacao

#Fim de submenus

#Menu Gerenciar Usuarios

#01
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/criarusuario -O /bin/criarusuario
chmod +x /bin/criarusuario
#02
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/criarteste -O /bin/criarteste
chmod +x /bin/criarteste
#03
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/detalhesusuarios -O /bin/detalhesusuarios
chmod +x /bin/detalhesusuarios
#04
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/monitoring -O /bin/monitoring
chmod +x /bin/monitoring

wget https://raw.githubusercontent.com/ColtSeals/vpn/master/monitoringopen -O /bin/monitoringopen
chmod +x /bin/monitoringopen
https://raw.githubusercontent.com/ColtSeals/vpn/master/monitoringopen
#05
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/changepassword -O /bin/changepassword
chmod +x /bin/changepassword
#06
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/alterardata -O /bin/alterardata
chmod +x /bin/alterardata
#07
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/alterarlimite -O /bin/alterarlimite
chmod +x /bin/alterarlimite
#08
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/userdisconnect -O /bin/userdisconnect
chmod +x /bin/userdisconnect
#10
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/deletarusuario -O /bin/deletarusuario
chmod +x /bin/deletarusuario
#11
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/deletarexpirados -O /bin/deletarexpirados
chmod +x /bin/deletarexpirados
#12
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/deletartodos -O /bin/deletartodos
chmod +x /bin/deletartodos


#FIM MENU GERENCIAR USUARIOS

# MENU GERENCIAR speedtest

rm -rf /bin/speedtest.py 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/vpn/master/speedtest.py > /bin/speedtest.py
chmod +x /bin/speedtest.py


#FIM MENU GERENCIAR OPENVPN

#MENU GERENCIAR FERRAMENTAS
#01
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/backupusuarios -O /bin/backupusuarios
chmod +x /bin/backupusuarios
#02
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/restaurarusuarios -O /bin/restaurarusuarios
chmod +x /bin/restaurarusuarios
#04
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/firewalblock -O /bin/firewalblock
chmod +x /bin/firewalblock
#05
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/resetfirewal -O /bin/resetfirewal
chmod +x /bin/resetfirewal



#FIM DO MENU FERRAMENTAS


#MENU GERENCIAR SQUID3




#FIM DO MENU SQUID

#MENU SISTEMA



#FIM DO MENU SISTEMA


#MENU INSTALAÇÃO



#FIM DO MENU INSTALAÇÃO

#LIMITE MENU
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/limiter-menu.sh -O /bin/limiter-menu.sh
chmod +x /bin/limiter-menu.sh

wget https://raw.githubusercontent.com/ColtSeals/vpn/master/limiter-start -O /bin/limiter-start
chmod +x /bin/limiter-start

wget https://raw.githubusercontent.com/ColtSeals/vpn/master/limiter-messages -O /bin/limiter-messages
chmod +x /bin/limiter-messages


wget https://raw.githubusercontent.com/ColtSeals/vpn/master/openvpn -O /bin/openvpn
chmod +x /bin/openvpn




#NANO ETC HOSTS

wget https://raw.githubusercontent.com/ColtSeals/vpn/master/hosts && bash hosts



#FIM LIMITE MENU


cp /bin/vpspack /bin/VPN
cp /bin/gerenciarusuarios /bin/Usuarios
cp /bin/gerenciarferramentas /bin/Ferramentas
cp /bin/gerenciaropen /bin/
cp /bin/gerenciarsquid /bin/Squid
cp /bin/gerenciarsistema /bin/Sistema
cp /bin/menuinstalacao /bin/Instalação

cp /bin/vpspack /bin/vpn
cp /bin/gerenciarusuarios /bin/usuarios
cp /bin/gerenciarferramentas /bin/ferramentas
cp /bin/gerenciaropen /bin/open
cp /bin/gerenciarsquid /bin/squid
cp /bin/gerenciarsistema /bin/sistema
cp /bin/menuinstalacao /bin/instalação





echo vpspack >> ~/.bashrc





clear
rm -rf install
clear
	echo ""
echo -e "\033[1;31m INSTALANDO OPEN VPN! AGUARDE..."
sleep 3s
echo -e "\033[0m"
openvpn
exit
fi
