#!/bin/bash
cd
if [ $(id -u) != 0 ]
then
echo "Execute o script como root"
exit
fi
echo -e "\033[1;30mInstalando...\033[0m"
mkdir /etc/VpsPackdir 2>/dev/null
mkdir /etc/VpsPackdir/limite 2>/dev/null
mkdir /etc/VpsPackdir/senha 2>/dev/null
rm -rf /bin/limite 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/estuda/master/limite > /bin/limite
chmod +x /bin/limite
rm -rf /bin/criarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/estuda/master/criarusuario > /bin/criarusuario
chmod +x /bin/criarusuario
rm -rf /bin/deletarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/estuda/master/deletarusuario > /bin/deletarusuario
chmod +x /bin/deletarusuario
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/redefinirusuario -O /bin/redefinirusuario
chmod +x /bin/redefinirusuario
rm -rf /bin/vpspack 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/estuda/master/vpspack > /bin/vpspack
chmod +x /bin/vpspack
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/ConfSquid -O /bin/ConfSquid
chmod +x /bin/ConfSquid
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/RemoverExpirados -O /bin/RemoverExpirados
chmod +x /bin/RemoverExpirados
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/openvpn -O /bin/openvpn
chmod +x /bin/openvpn
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/Teste -O /bin/Teste
chmod +x /bin/Teste
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/BadVpn.sh -O /bin/BadVpn.sh
chmod +x /bin/BadVpn.sh
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/Monitorar -O /bin/Monitorar
chmod +x /bin/Monitorar
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/RemoverLimite -O /bin/RemoverLimite
chmod +x /bin/RemoverLimite
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/MudarNome -O /bin/MudarNome
chmod +x /bin/MudarNome
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/FirewallBlock -O /bin/FirewallBlock
chmod +x /bin/FirewallBlock
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/FirewallReset -O /bin/FirewallReset
chmod +x /bin/FirewallReset
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/addhost -O /bin/addhost
chmod +x /bin/addhost
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/removerhost -O /bin/removerhost
chmod +x /bin/removerhost
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/Backup -O /bin/Backup
chmod +x /bin/Backup
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/Restaurar -O /bin/Restaurar
chmod +x /bin/Restaurar
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/DetalhesUsuarios -O /bin/DetalhesUsuarios
chmod +x /bin/DetalhesUsuarios
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/Banner -O /bin/Banner
chmod +x /bin/Banner
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/LimpadorCache -O /bin/LimpadorCache 
chmod +x /bin/LimpadorCache 
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/VNC -O /bin/VNC
chmod +x /bin/VNC
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/tcptweaker -O /bin/tcptweaker
chmod +x /bin/tcptweaker
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/DeletarTodos -O /bin/DeletarTodos
chmod +x /bin/DeletarTodos
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/Ajuda -O /bin/Ajuda
chmod +x /bin/Ajuda
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/Creditos -O /bin/Creditos
chmod +x /bin/Creditos
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/Telegram -O /bin/Telegram
chmod +x /bin/Telegram
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/UpdateVPS -O /bin/UpdateVPS
chmod +x /bin/UpdateVPS
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/Desinstalar -O /bin/Desinstalar
chmod +x /bin/Desinstalar
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/SistemaDetalhes -O /bin/SistemaDetalhes
chmod +x /bin/SistemaDetalhes
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/hardware -O /bin/hardware
chmod +x /bin/hardware
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/HardwareGeral -O /bin/HardwareGeral 
chmod +x /bin/Desinstalar
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/RAM -O /bin/RAM
chmod +x /bin/RAM
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/cpu -O /bin/cpu
chmod +x /bin/cpu
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/HD -O /bin/HD
chmod +x /bin/HD
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/MelhorarVelocidade -O /bin/MelhorarVelocidade
chmod +x /bin/MelhorarVelocidade
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/PasswordRoot -O /bin/PasswordRoot
chmod +x /bin/PasswordRoot
wget https://raw.githubusercontent.com/ColtSeals/estuda/master/speedtest -O /bin/speedtest
chmod +x /bin/speedtest

sed -i '3i\127.0.0.1 portalrecarga.vivo.com.br\' /etc/hosts

cp /bin/limite /bin/Limite
cp /bin/criarusuario /bin/CriarUsuario
cp /bin/criarusuario /bin/criar
cp /bin/ConfSquid /bin/confsquid
cp /bin/ConfSquid /bin/squid
cp /bin/RemoverExpirados /bin/removerexpirados
cp /bin/RemoverExpirados /bin/expiradosdel
cp /bin/Monitorar /bin/monitor
cp /bin/Monitorar /bin/monitorar
cp /bin/RemoverLimite /bin/removerlimite
cp /bin/RemoverLimite /bin/limitedel
cp /bin/MudarNome /bin/mudarnome
cp /bin/redefinirusuario /bin/RedefinirUsuario
cp /bin/redefinirusuario /bin/redefiniruser
cp /bin/redefinirusuario /bin/redefinir
cp /bin/deletarusuario /bin/DeletarUsuario
cp /bin/deletarusuario /bin/deletaruser
cp /bin/FirewallBlock /bin/firewallblock
cp /bin/FirewallBlock /bin/fiblock
cp /bin/FirewallReset /bin/firewallreset
cp /bin/FirewallReset /bin/fireset
cp /bin/addhost /bin/AddHost
cp /bin/removerhost /bin/RemoverHost
cp /bin/removerhost /bin/hostdel
cp /bin/Backup /bin/backup
cp /bin/Restaurar /bin/restaurar
cp /bin/DetalhesUsuarios /bin/detalhesusuarios
cp /bin/DetalhesUsuarios /bin/detalhesuser
cp /bin/DetalhesUsuarios /bin/Detalhes
cp /bin/Banner /bin/banner
cp /bin/LimpadorCache /bin/limpadorcache
cp /bin/VNC /bin/vnc
cp /bin/tcptweaker /bin/TCPTweaker
cp /bin/tcptweaker /bin/tcp
cp /bin/DeletarTodos /bin/deletartodos
cp /bin/Telegram /bin/telegram
cp /bin/Creditos /bin/creditos
cp /bin/Ajuda /bin/ajuda
cp /bin/Desinstalar /bin/desinstalar
cp /bin/SistemaDetalhes /bin/sistemadetalhes
cp /bin/SistemaDetalhes /bin/detalhessistem
cp /bin/vpspack /bin/menu
cp /bin/vpspack /bin/MenuVPS
cp /bin/vpspack /bin/vps
cp /bin/vpspack /bin/menuvps

sed -i '3i\127.0.0.1 d1n212ccp6ldpw.cloudfront.net\' /etc/hosts


echo -e "\033[1;31m•••••> \033[01;37mScript Edited ••ColtSeals TecnologY•• \033[0m"
echo -e "\033[1;32m•••••> A Internet aproxima quem está longe e afasta quem está perto!"
echo -e "\033[1;32m•••••> TELEGRAM GRUPO: @NerdologiaVps"
echo -e "\033[1;32m•••••> TELEGRAM CANAL: @VpsNerdologia"
echo -e "\033[1;32mInstalacao concluida\n\033[1;30mExecute:"
echo -e "\n\033[1;32mvps \033[1;30mMenu com opcoes"
echo -e "\033[1;32mcriarusuario \033[1;30mCriar usuario com data e limite"
echo -e "\033[1;32mdeletarusuario \033[1;30mDeletar usuario ou apenas desconectar"
echo -e "\033[1;32mredefinirusuario \033[1;30mAlterar data, senha, etc, de um usuario"
echo -e "\033[1;32mlimite \033[1;30mLimite de logins simultaneos\033[0m"
rm -rf install
