#!/bin/bash
cd
if [ $(id -u) != 0 ]
then
echo "Execute o script como root"
exit
fi
echo -e "\033[1;30mInstalando...\033[0m"
mkdir /etc/VpsPackdir 2>/dev/null
mkdir /etc/VpsPackdir/limite 2>/dev/null
mkdir /etc/VpsPackdir/senha 2>/dev/null

if [ ! -d "/home/DATABASE" ]; then
  mkdir /home/DATABASE; mkdir /home/DATABASE/Backups; touch /home/DATABASE/bannerssh.txt; touch /home/DATABASE/messages.txt; touch /home/DATABASE/users.db; awk -F : '$3 >= 500 { print $1 " **** 1" }' /etc/passwd | grep -v "nobody" | sort > /home/DATABASE/users.db
fi
#Menu Principal

rm -rf /bin/vpspack 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/vpn/master/vpspack > /bin/vpspack
chmod +x /bin/vpspack
#Fim do Menu Principal

rm -rf /bin/limite 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/vpn/master/limite > /bin/limite
chmod +x /bin/limite
#Fim Menu

#Menus Gerenciadores
#01
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/gerenciarusuarios -O /bin/gerenciarusuarios
chmod +x /bin/gerenciarusuarios
#02
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/gerenciarferramentas -O /bin/gerenciarferramentas
chmod +x /bin/gerenciarferramentas
#04
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/gerenciarsquid -O /bin/gerenciarsquid
chmod +x /bin/gerenciarsquid
#05
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/gerenciarsistema -O /bin/gerenciarsistema
chmod +x /bin/gerenciarsistema
#06
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/menuinstalacao -O /bin/menuinstalacao
chmod +x /bin/menuinstalacao

#Fim de submenus

#Menu Gerenciar Usuarios
#01
#ADMVPS
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/createuser.sh -O /bin/criarusuario.sh
chmod +x /bin/criarusuario.sh

wget https://raw.githubusercontent.com/ColtSeals/vpn/master/monitoring.sh -O /bin/monitor.sh
chmod +x /bin/monitoring.sh
#FIM DO ADM VPS USUARIOS

rm -rf /bin/criarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/vpn/master/criarusuario > /bin/criarusuario
chmod +x /bin/criarusuario
#02
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/criarteste -O /bin/criarteste
chmod +x /bin/criarteste
#03
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/detalhesusuarios -O /bin/detalhesusuarios
chmod +x /bin/detalhesusuarios
#04
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/monitoramento -O /bin/monitoramento
chmod +x /bin/monitoramento
#05
rm -rf /bin/redefinirusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/vpn/master/redefinirusuario > /bin/redefinirusuario
chmod +x /bin/redefinirusuario
#06
rm -rf /bin/deletarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/vpn/master/deletarusuario > /bin/deletarusuario
chmod +x /bin/deletarusuario
#07
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/deletarexpirados -O /bin/deletarexpirados
chmod +x /bin/deletarexpirados
#08
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/deletartodos -O /bin/deletartodos
chmod +x /bin/deletartodos



#FIM MENU GERENCIAR USUARIOS

# MENU GERENCIAR speedtest

rm -rf /bin/speedtest.py 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/RicKbrL/VpsPack/master/speedtest.py > /bin/speedtest.py
chmod +x /bin/speedtest.py


#FIM MENU GERENCIAR OPENVPN

#MENU GERENCIAR FERRAMENTAS
#01
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/backupusuarios -O /bin/backupusuarios
chmod +x /bin/backupusuarios
#02
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/restaurarusuarios -O /bin/restaurarusuarios
chmod +x /bin/restaurarusuarios
#03
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/speedtest -O /bin/speedtest
chmod +x /bin/speedtest
#04
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/firewalblock -O /bin/firewalblock
chmod +x /bin/firewalblock
#05
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/resetfirewal -O /bin/resetfirewal
chmod +x /bin/resetfirewal

#FIM DO MENU FERRAMENTAS

#MENU GERENCIAR OPEN
#01
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/criarusuarioopen -O /bin/criarusuarioopen
chmod +x /bin/criarusuarioopen
#02
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/dataopen -O /bin/dataopen
chmod +x /bin/dataopen
#03
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/monitoropen -O /bin/monitoropen
chmod +x /bin/monitoropen
#04
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/genericoopen -O /bin/genericoopen
chmod +x /bin/genericoopen
#05
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/deluseropen -O /bin/deluseropen
chmod +x /bin/deluseropen
#06
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/deltodosopen -O /bin/deltodosopen
chmod +x /bin/deltodosopen
#07
wget https://raw.githubusercontent.com/ColtSeals/vpn/master/desinstalaropen -O /bin/desinstalaropen
chmod +x /bin/desinstalaropen

wget https://raw.githubusercontent.com/ColtSeals/vpn/master/createuser.sh -O /bin/createuser.sh
chmod +x /bin/createuser.sh

wget https://raw.githubusercontent.com/ColtSeals/vpn/master/monitoring.sh -O /bin/monitoring.sh
chmod +x /bin/monitoring.sh





#FIM DO MENU GERENCIAR OPEN

#MENU GERENCIAR SQUID3




#FIM DO MENU SQUID

#MENU SISTEMA



#FIM DO MENU SISTEMA


#MENU INSTALAÇÃO



#FIM DO MENU INSTALAÇÃO


wget https://raw.githubusercontent.com/ColtSeals/vpn/master/openvpn -O /bin/openvpn
chmod +x /bin/openvpn




#NANO ETC HOSTS

wget https://raw.githubusercontent.com/ColtSeals/vpn/master/hosts && bash hosts





cp /bin/vpspack /bin/VPN
cp /bin/gerenciarusuarios /bin/Usuarios
cp /bin/gerenciarferramentas /bin/Ferramentas
cp /bin/gerenciaropen /bin/
cp /bin/gerenciarsquid /bin/Squid
cp /bin/gerenciarsistema /bin/Sistema
cp /bin/menuinstalacao /bin/Instalação

cp /bin/vpspack /bin/vpn
cp /bin/gerenciarusuarios /bin/usuarios
cp /bin/gerenciarferramentas /bin/ferramentas
cp /bin/gerenciaropen /bin/open
cp /bin/gerenciarsquid /bin/squid
cp /bin/gerenciarsistema /bin/sistema
cp /bin/menuinstalacao /bin/instalação
echo vpspack >> ~/.bashrc


clear
echo -e "\033[1;32mInstalacao concluida\n\033[1;30mExecute:"
echo -e "\n\033[1;32mvpspack \033[1;30mMenu com opcoes"
echo -e "\033[1;32mcriarusuario \033[1;30mCriar usuario com data e limite"
echo -e "\033[1;32mdeletarusuario \033[1;30mDeletar usuario ou apenas desconectar"
echo -e "\033[1;32mredefinirusuario \033[1;30mAlterar data, senha, etc, de um usuario"
echo -e "\033[1;32mlimite \033[1;30mLimite de logins simultaneos\033[0m"
rm -rf install
clear
	echo ""
echo -e "\033[1;31m INSTALANDO OPEN VPN! AGUARDE..."
sleep 3s
echo -e "\033[0m"
openvpn
exit
fi
