#!/bin/bash
cd
if [ $(id -u) != 0 ]
then
echo "Execute o script como root"
exit
fi
echo -e "\033[01;34;47mM\033[01;31me\033[01;33mn\033[01;34mu\033[01;32mV\033[01;34;47mP\033[01;31mS"
echo ""
echo "        Edited @ColtSeals"
echo "        NERDOLOGIA VPS"
echo "        NETFREE: FOREVER"
echo "        Nome: MenuVPS 1.0"
echo ""
read -p "De enter para continuar..."
clear
echo -e "\033[1;30mInstalando...\033[0m"
mkdir /etc/VpsPackdir 2>/dev/null
mkdir /etc/VpsPackdir/limite 2>/dev/null
mkdir /etc/VpsPackdir/senha 2>/dev/null
rm -rf /bin/limite 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/VPSMenu/master/limite > /bin/limite
chmod +x /bin/limite
rm -rf /bin/criarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/VPSMenu/master/criarusuario > /bin/criarusuario
chmod +x /bin/criarusuario
rm -rf /bin/deletarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/VPSMenu/master/deletarusuario > /bin/deletarusuario
chmod +x /bin/deletarusuario
rm -rf /bin/redefinirusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/VPSMenu/master/redefinirusuario > /bin/redefinirusuario
chmod +x /bin/redefinirusuario
rm -rf /bin/vpspack 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/VPSMenu/master/vpspack > /bin/vpspack
chmod +x /bin/vpspack
rm -rf /bin/speedtest.py 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/ColtSeals/VPSMenu/master/speedtest.py > /bin/speedtest.py
chmod +x /bin/speedtest.py
wget https://raw.githubusercontent.com/ColtSeals/VPSMenu/master/OpenVPN -O /bin/OpenVPN
chmod +x /bin/OpenVPN
sed -i -e 's/\r$//' /bin/OpenVPN
clear
echo -e "\033[1;31m•••••> \033[01;37mScript Edited ••ColtSeals TecnologY•• \033[0m"
echo -e "\033[1;32m•••••> A Internet aproxima quem está longe e afasta quem está perto!"
echo -e "\033[1;32m•••••> TELEGRAM GRUPO: @NerdologiaVps"
echo -e "\033[1;32m•••••> TELEGRAM CANAL: @VpsNerdologia"
echo -e "\033[1;32mInstalacao concluida\n\033[1;30mExecute:"
echo -e "\n\033[1;32mMenuVPS \033[1;30mMenu com opcoes"
echo -e "\033[1;32mcriarusuario \033[1;30mCriar usuario com data e limite"
echo -e "\033[1;32mdeletarusuario \033[1;30mDeletar usuario ou apenas desconectar"
echo -e "\033[1;32mredefinirusuario \033[1;30mAlterar data, senha, etc, de um usuario"
echo -e "\033[1;32mlimite \033[1;30mLimite de logins simultaneos\033[0m"
echo -e "\033[1;32mopen \033[1;30m(Configura e Gerencia Usuarios .ovpn)\033[0m"
rm -rf install
cp /bin/vpspack /bin/vps
cp /bin/vpspack /bin/MenuVPS
cp /bin/OpenVPN /bin/open
