#!/bin/bash
while truee true; do
echo -e "\033[1;37m -------------------------------------------------------\033[0m"
   :               Conexoes S   \033[0m"
echo -e "\033[1;37m -------------------------------------------------------\033[0m"
      r usur in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi systemd-[a-z] |grep -vi systemd-[0-9]`; do
	
        
