#!/bin/bash
clear
echo "Edited by @ColtSeals"
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Conectando ao NerdologiaVPS..."
sleep 0.4
echo "Checando Permissão..."
sleep 0.2
echo -e "${green}Permissão Aceita...${NC}"
sleep 0.2

clear
while true; do
echo -e "\033[1;37m •••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' "MONITOR MenuVPS" ; tput sgr0
echo -e "\033[1;37m •••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"

echo -e "\033[1;37m •••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"
echo -e " \033[47;30m   Usuario                          Conectado/Limite \033[0m"
echo -e "\033[1;37m •••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"
for usur in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi systemd-[a-z] |grep -vi systemd-[0-9] |sort`; do
if [ -f /etc/VpsPackdir/limite/$usur ]; then
limite=$(cat -n /etc/VpsPackdir/limite/$usur |awk '$1 = 1 {print $2}')
else
limite=null
fi
usurnum="$(ps -u $usur |grep sshd |wc -l)\033[1;30m/\033[1;33m$limite"
echo -e "\033[1;33m    $(printf '%-41s%s' $usur $usurnum) \033[0m"
echo -e "\033[1;37m -----------------------------------------------------\033[0m"
  done
  echo ""
  echo -e "\033[01;36m APERTE CTRL+C PARA SAIR DO MONITOR..."
  sleep 6s
done
