#!/bin/bash

while true; do

echo -e "\033[1;37m ••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"
echo -e " \033[47;30m                      MONITOR                      \033[0m"
echo -e "\033[1;37m ••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"

echo -e "\033[1;37m ••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"
echo -e " \033[47;30m   Usuario              :           Conexão|Limite \033[0m"
echo -e "\033[1;37m ••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"
        for usur in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi systemd-[a-z] |grep -vi systemd-[0-9] |sort`; do
	if [ -f /etc/VpsPackdir/limite/$usur ]
	then
	if [[ $(cat /etc/VpsPackdir/limite/$usur) == "" ]]
	then
	limite=null
	else
	limite=$(cat /etc/VpsPackdir/limite/$usur)
	fi
	else
	limite=null
	fi
	usurnum="$(ps -u $usur |grep sshd |wc -l)/$limite"
        echo -e "\033[1;33m    $(printf '%-41s%s' $usur $usurnum) \033[0m"
        echo -e "\033[1;37m ••••••••••••••••••••••••••••••••••••••••••••••••••••\033[0m"
        done
sleep 6s
clear
done
