#!/bin/bash

function CTRL () 
{
vpn
exit
}
trap CTRL SIGINT

while true; do
  clear
  echo ""
  echo -ne " \033[0;30;46m"; printf '%38s%-28s\n' "MONITOR OPEN/SSH"; echo -ne "\033[0m"
  echo -e " \033[01;37;44m USUÁRIO                    CONEXÃO                        STATUS \033[0m"
  echo ""
  cat /etc/passwd | grep -v "nobody" | awk  -F : '$3 >= 500 {print  $1}' | sort > /tmp/users.txt
  cat /tmp/users.txt | sort | while read MONITOR; do
    USERS=$(echo $MONITOR | cut -d " " -f1)
    NUMBER1=$(ps -u $USERS | grep sshd | wc -l)
    NUMBER2=$(grep "$USERS" /etc/openvpn/openvpn-status.log | wc -l)
    if [ $NUMBER1 -gt 0 -a $NUMBER2 -gt 0 ]; then
      echo -ne " \033[01;32m"; printf '%-28s%-31s%s\n' " $USERS" "OpenVPN/SSH" "ONLINE"
    elif [ $NUMBER1 -gt 0 ]; then
      echo -ne " \033[01;32m"; printf '%-28s%-31s%s\n' " $USERS" "SSH" "ONLINE"
    elif [ $NUMBER2 -gt 0 ]; then
      echo -ne " \033[01;32m"; printf '%-28s%-31s%s\n' " $USERS" "OPENVPN" "ONLINE"
    else
      echo -ne " \033[01;31m"; printf '%-28s%-31s%s\n' " $USERS" "OFFLINE" "OFFLINE"
    fi
    echo -e "\033[7;30;46m ------------------------------------------------------------------\033[0m"
  done
  echo ""
  echo -e "\033[01;36m APERTE CTRL+C PARA VOLTAR AO MENU..."
  sleep 5s
done
