#!/bin/bash

clear
echo -e "\033[1;31mATENÇÃO: \033[1;35m Essa senha será usada para entrar no seu servidor, guardea em um lugar seguro. Mesmo digitando não aparecerá nada, mas esta tudo bem, é assim mesmo. Precione \033[1;31mENTER \033[1;35mpara continuar ou \033[1;31mCTRL + C \033[1;35mpara cancelar\033[0m"
read  #enter
passwd
sleep 2 
2