#!/bin/bash
echo -e "\033[1;37mPara Cancelar \033[1;33m \033[1;33mmCtrl + C\033[1;33m"
echo -e "\033[1;31mHosts atualmente permitidos\n\n\033[1;32m$(cat /etc/payloads)\n\033[0m"
echo -ne "\033[1;37mDeseja remover todos os Hosts? \033[0m"
read host
hosts = $(cat /etc/payloads |grep -v $host)
echo "$hosts" > /etc/payloads
squid -k reconfigure >/dev/null 2>/dev/null
squid3 -k reconfigure >/dev/null 2>/dev/null
echo -e "\n\033[1;32mTodos Hosts Removidos com SUCESSO.\033[0m"
