#!/bin/bash
echo -e "\033[1;31mHosts atualmente permitidos\n\n\033[1;32m$(cat /etc/payloads)\n\033[0m"
echo -ne "\033[1;37mSim Aperte enter \033[0m"
echo -ne "\033[1;37mCancelar Ctrl+c \033[0m"
echo -ne "\033[1;37mDeseja Remover Todas Hosts?: \033[0m"
read host
echo "$hosts" > /etc/payloads
squid -k reconfigure >/dev/null 2>/dev/null
squid3 -k reconfigure >/dev/null 2>/dev/null
echo -e "\n\033[1;32mTodas as Hosts Removidas com SUCESSO!\033[0m"
