#!/bin/bash

clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' "TESTE DE CONEXÃO" ; tput sgr0
echo ""
echo "        Edited @ColtSeals"
echo "        NERDOLOGIA VPS"
echo "        NETFREE: FOREVER"
echo "        Nome: MenuVPS 1.0"
echo ""
read -p "De enter para continuar..."
clear
echo -e "\033[1;31mRealizando testes...\033[0m"
ping=$(ping -c1 google.com |awk '{print $8 $9}' |grep -v loss |cut -d = -f2 |sed ':a;N;s/\n//g;ta')
echo -e "\033[1;36mPing:\033[0m $ping"
velo=$(speedtest.py |grep load:)
echo -e "$velo"
