#!/bin/bash

function CTRL() 
{
h
exit
}
trap CTRL SIGINT

while true; do
  clear
  echo ""
  echo -e " \033[01;37;44m USUARIOS      CONEXÃO/LIMITE     TEMPO DE CONEXÃO     STATUS \033[0m"
  echo ""
  cat /etc/passwd | grep -v "nobody" | awk  -F : '$3 >= 500 {print  $1}' | sort > /tmp/users.txt
  cat /tmp/users.txt | sort | while read MONITOR; do
  	MONITORING3=$(echo $MONITOR | cut -d " " -f1)
    MONITORING1=$ps -u $MONITORING3 | grep sshd | wc -l)
    MONITORING2=$(grep "$MONITORING3" /etc/openvpn/openvpn-status.log | wc -l)
    if [ "$MONITORING2" -gt "0" ]; then
    	TIME=$(ps -o etime $(ps -u $MONITORING1 |grep sshd |awk 'NR==1 {print $1}')|awk 'NR==2 {print $1}')
      echo -ne " \033[01;33m"; printf '%-21s%-16s%-7s%s' " $MONITORING1" "$MONITORING2/$MONITORING3 " "$TIME"; echo -e "          \033[01;32m ONLINE" 
    else
      echo -ne " \033[01;33m"; printf '%-21s%-16s%-7s%s' " $MONITORING1" "$MONITORING2/$MONITORING3 " "00:00"; echo -e "          \033[01;31m OFFLINE" 
    fi
    echo -e "\033[01;30m --------------------------------------------------------------"
  done
  echo ""
  echo -e "\033[01;36m APERTE CTRL+C PARA VOLTAR AO MENU..."
  sleep 10s
done
