#!/bin/sh
#
# translate - Babel Fish front-end.
# Copyright (C) 2006 Herbert Alexander Faleiros
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# Herbert Alexander Faleiros aka ratmmmam <herbert@faleiros.eti.br>
#

HOST=http://babelfish.altavista.com/tr
OPTS="-dump -source"

LNGS=`lynx $OPTS $HOST | grep option | sort -u | \
        sed -r '1d;s/.+=\"(.+)/\\t\1/g;s/\">/ = /g;s/<.+//g'`

function translate() {

        echo -n $i | sed -r 's/_.+//'
        echo ": $2"

        echo -n $i | sed -r 's/.+_//'
        echo -n ": "

        lynx $OPTS "$HOST?trtext=$2&lp=$1" | grep div | \
        sed -r 's/(.+;>)(.+)(<\/d.+)/\2/' | sed -n 3p

        exit 0
}

function usage() {

        echo -e "\n  Usage: $0 lang_lang \"input text\""
        echo "Example: $0 pt_en \"Feliz ano novo\""
        echo -e "\n\tAvailable languages/possibilities:\n"
        echo -e "$LNGS\n"

        exit 1
}

[ "$2" = "" ] && usage

for i in `echo $LNGS | tr -s ' ' '\n' | sed -rn '/_/p'`; do
        [ "$1" = "$i" ] && translate $1 "$2"
done

usage
