#!/bin/bash
function limite(){
mkdir /etc/usuarios 1>/dev/null 2>/dev/null
userrc=$(echo $1 |sed 's/-/k/g' |sed 's/0/a/g' |sed 's/1/b/g' |sed 's/2/c/g' |sed 's/3/d/g' |sed 's/4/e/g' |sed 's/5/f/g' |sed 's/6/g/g' |sed 's/7/h/g' |sed 's/8/i/g' |sed 's/9/j/g')
sustenido=$
limpcron=$(cat /etc/crontab |grep -v /$1.sh)
echo "$limpcron" > /etc/crontab
echo "#!/bin/bash" > /etc/usuarios/$1.sh
echo ""$userrc"t="$sustenido"(ps -u $1 |grep 'sshd' |wc -l)" >> /etc/usuarios/$1.sh
echo "if [ "$sustenido""$userrc"t -gt $2 ]" >> /etc/usuarios/$1.sh
echo "then" >> /etc/usuarios/$1.sh
echo $userrc"pidi="$sustenido"(ps -u $1 |grep sshd |awk {'print "$sustenido"1'})" >> /etc/usuarios/$1.sh
echo 'echo "'$sustenido''$userrc''pidi'" > /etc/usuarios/pid'$userrc >> /etc/usuarios/$1.sh
echo $userrc"pid="$sustenido"(cat -n /etc/usuarios/pid$userrc |awk ' "$sustenido"1 > $2 { print "$sustenido"NF }')" >> /etc/usuarios/$1.sh
echo "kill -9 $sustenido"$userrc"pid" >> /etc/usuarios/$1.sh
echo "fi" >> /etc/usuarios/$1.sh
mkdir /etc/tempo 1>/dev/null 2>/dev/null
echo "#!/bin/bash" > /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
mkdir /etc/VpsPackdir 1>/dev/null 2>/dev/null
mkdir /etc/VpsPackdir/limite 1>/dev/null 2>/dev/null
echo "$2" > /etc/VpsPackdir/limite/$1
echo "*/1 * * * * root bash /etc/tempo/$1.sh" >> /etc/crontab
echo -e "\033[1;37mUsuario: \033[1;31m[\033[1;37m$1\033[1;31m]\033[1;37m Limite: \033[1;31m[\033[1;37m$2\033[1;31m] \033[1;37m[\033[1;31mLimite Aplicado\033[1;37m]  \033[0m"
}
mkdir /etc/VpsPackdir 1>/dev/null 2>/dev/null
mkdir /etc/VpsPackdir/senha 1>/dev/null 2>/dev/null
if [ $(id -u) -eq 0 ]
then
	echo -e "\033[1;32mNome do novo usuario:\033[0;37m"; read -p " " name
	echo -e "\033[1;32mSenha para o usuario $name:\033[0;37m"; read -p " " pass
	echo -e "\033[1;32mQuantos dias usuario $name deve durar:\033[0;37m"; read -p " " daysrnf
	echo -e "\033[1;32mLimite de logins simultaneos:\033[0;37m"; read -p " " limituser
	echo -e "\033[0m"
	if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
	then
		echo -e "\033[1;31mUsuario $name ja existe\033[0m"
	else
		valid=$(date '+%C%y-%m-%d' -d " +$daysrnf days")
		datexp=$(date "+%d/%m/%Y" -d "+ $daysrnf days")
		useradd -M -s /bin/false $name -e $valid
		(echo $pass; echo $pass)|passwd $name 2>/dev/null
		limite $name $limituser
		echo -e "\033[1;36mUsuario: \033[0m$name"
		echo -e "\033[1;36mSenha: \033[0m$pass"
		echo -e "\033[1;36mExpira:\033[0m $datexp"
	    echo "$pass" > /etc/VpsPackdir/senha/$name
	fi
else
	if echo $(id) |grep sudo > /dev/null
	then
	echo "Seu usuario esta no grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	echo -e "Ou execute o Usercreate como sudo. \033[1;31msudo Usercreate\033[0m"
	else
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	fi
fi

