#!/bin/bash

ip=$(wget -qO- ipv4.icanhazip.com)

if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Voce não é root"
	echo "Seu usuario esta no grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	exit
	else
	clear
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	exit
	fi
fi

if [ -d /etc/VpsPackdir ]
then
echo ""
else
mkdir /etc/VpsPackdir
fi

if [ -d /etc/VpsPackdir/senha ]
then
echo ""
else
mkdir /etc/VpsPackdir/senha
fi

if [ -d /etc/VpsPackdir/limite ]
then
echo ""
else
mkdir /etc/VpsPackdir/limite
fi


clear
if [[ $1 == "" ]]
then
clear

dia=$(date | awk {'print $3'})
mes=$(date | awk {'print $2'})
ano=$(date | awk {'print $6'})
if [[ "$mes" = "Jan" || "$mes" = "Jan" ]]; then
mes=01
elif [[ "$mes" = "Feb" || "$mes" = "Fev" ]]; then
mes=02
elif [[ "$mes" = "Mar" || "$mes" = "Mar" ]]; then
mes=03
elif [[ "$mes" = "Apr" || "$mes" = "Abr" ]]; then
mes=04
elif [[ "$mes" = "May" || "$mes" = "Mai" ]]; then
mes=05
elif [[ "$mes" = "Jun" || "$mes" = "Jun" ]]; then
mes=06
elif [[ "$mes" = "Jul" || "$mes" = "Jul" ]]; then
mes=07
elif [[ "$mes" = "Ago" || "$mes" = "Ago" ]]; then
mes=08
elif [[ "$mes" = "Set" || "$mes" = "Sep" ]]; then
mes=09
elif [[ "$mes" = "Out" || "$mes" = "Oct" ]]; then
mes=10
elif [[ "$mes" = "Nov" || "$mes" = "Nov" ]]; then
mes=11
elif [[ "$mes" = "Dec" || "$mes" = "Dez" ]]; then
mes=12
fi

ama="\033[01;33m"
b="\033[01;37m"
v="\033[01;32m"
Ver="\033[01;31m"


  echo -e "                      "$v"DATA: "$ama"$dia"$b"/"$ama"$mes"$b"/"$ama"$ano "
else
  echo -e ""$v"DATA: "$ama"$dia"$b"/"$ama"$mes"$b"/"$ama"$ano "
fi

echo -e "\033[01;35m  •\033[01;32m IP da VPS:\033[1;33m $ip"
system=$(cat /etc/issue.net)
if [ "$system" ]
then
echo -e "\033[01;35m  •\033[01;32m sistema Operacional:\033[1;33m $system"
else
echo "Sistema Operacional: Not Available"
fi

echo -e "\033[5;36;40m ==========================================================\033[0m"
echo -e "\033[7;30;47m  ®Script\033[0m \033[7;30;41mEdited:\033[0m \033[0m \033[0;36;40m@Colt\033[5;37;40mSeals\033[0m"
echo -e "\033[7;30;47m  ®TELEGRAM\033[0m \033[7;30;41mCANAL:\033[0m \033[0m \033[0;36;40m@Vps\033[5;37;40mNerdologia\033[0m"
echo -e "\033[5;36;40m ==========================================================\033[0m"
echo -e "\033[7;30;46m  Para Acessar este menu digite:\033[5;37;40m VPN \033[0m"
echo -e "\033[5;36;40m ==========================================================\033[0m"

echo -e "\033[01;36m║\033[1;37m00\033[1;36m║\033[5;31;40m•\033[0m\033[01;37m SAIR \033[5;31;40m=\033[0m \033[7;36;40m Sair do Menu VPN. \033[0m"
echo -e "\033[01;36m║\033[1;37m01\033[1;36m║\033[5;31;40m•\033[0m\033[01;37m GERENCIAR USUÁRIOS \033[5;31;40m=\033[0m \033[7;36;40m Criar usuários, redefinir etc \033[0m"
echo -e "\033[01;36m║\033[1;37m02\033[1;36m║\033[5;31;40m•\033[0m\033[01;37m GERENCIAR USUÁRIOS OpenVPN \033[5;31;40m=\033[0m \033[7;36;40m Menu OPENVPN \033[0m"
echo -e "\033[01;36m║\033[1;37m03\033[1;36m║\033[5;31;40m•\033[0m\033[01;37m GERENCIAR FERRAMENTAS \033[5;31;40m=\033[0m \033[7;36;40m Add hosts,excluir hosts etc \033[0m"
echo -e "\033[01;36m║\033[1;37m04\033[1;36m║\033[5;31;40m•\033[0m\033[01;37m ATUALIZAÇÃO \033[5;31;40m=\033[0m \033[7;36;40m Atualizar Sistema \033[0m"
echo -e "\033[01;36m║\033[1;37m05\033[1;36m║\033[5;31;40m•\033[0m\033[01;37m MENU INSTALAÇÃO \033[5;31;40m=\033[0m \033[7;36;40m Instalações Opcionais \033[0m"
echo -e "\033[01;36m║\033[1;37m06\033[1;36m║\033[5;31;40m•\033[0m\033[01;37m SOBRE \033[5;31;40m=\033[0m \033[7;36;40m Informações sobre Desenvolvedor \033[0m"
echo -e "\033[5;36;40m ==========================================================\033[0m"
echo -e "\033[5;31;40m    •\033[0m\033[01;37m Digite uma Opção:\033[0;37m"; read -p " " opcao
else
opcao=$1
fi
case $opcao in
  0 | 00 )
   exit;;
  1 | 01 )
   gerenciarusuarios;;
  3 | 03 )
   gerenciaropen;;
  4 | 04 )
   gerenciarferramentas;;
  5 | 05 )
   atualização;;
  6 | 06 )
   menuinstalação;;
  7 | 07 )
   sobre;;
esac
