#!/bin/bash

clear
if [ -f /bin/VpsPack ]
  then
  echo -e "\033[1;31mVpsPack \033[1;36mjá está instalado.\033[0m"
  true
  if [ -f /bin/PackSSH ]
  then
  echo -e "\033[1;31mPackSSH \033[1;36mjá está instalado.\033[0m"
  true
  fi
  if [ -f /bin/CONFVPS ]
  then
  echo -e "\033[1;31mCONFVPS \033[1;36mjá está instalado,  a instalação do mesmo não é necessária.\033[0m"
  true
  fi
fi
echo -e "\033[1;36m Escolha uma das opçoẽs desejado abaixo.\033[0m"
echo -e "\033[1;31mPara sair pressione Ctrl + C\033
\033[1;36m 1|VpsPack
\033[1;36m 2|CONFVPS
\033[1;36m 3|PackSSH
\033[1;36m 4|Voltar\033[0m"
read -p "Opção:" opcao

case $opcao in
 1)
  2031;;
 2) 
  2032;;
  3) 
   2033;;
  4)
   2;;
  *) 
  id > /dev/null 2> /dev/null
esac
